// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct BuildingTypeData {
  uint32 category;
  uint32 tribe;
  uint32 inputItem1;
  uint64 inputQty1;
  uint32 inputItem2;
  uint64 inputQty2;
  uint32 outputItem1;
  uint64 outputQty1;
  uint32 outputItem2;
  uint64 outputQty2;
  string name;
}

library BuildingType {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "aldea", name: "BuildingType", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462616c6465610000000000000000004275696c64696e675479706500000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00380a0104040408040804080408000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint32)
  Schema constant _keySchema = Schema.wrap(0x0004010003000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint32, uint32, uint32, uint64, uint32, uint64, uint32, uint64, uint32, uint64, string)
  Schema constant _valueSchema = Schema.wrap(0x00380a0103030307030703070307c50000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "buildingId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](11);
    fieldNames[0] = "category";
    fieldNames[1] = "tribe";
    fieldNames[2] = "inputItem1";
    fieldNames[3] = "inputQty1";
    fieldNames[4] = "inputItem2";
    fieldNames[5] = "inputQty2";
    fieldNames[6] = "outputItem1";
    fieldNames[7] = "outputQty1";
    fieldNames[8] = "outputItem2";
    fieldNames[9] = "outputQty2";
    fieldNames[10] = "name";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get category.
   */
  function getCategory(uint32 buildingId) internal view returns (uint32 category) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get category.
   */
  function _getCategory(uint32 buildingId) internal view returns (uint32 category) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set category.
   */
  function setCategory(uint32 buildingId, uint32 category) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((category)), _fieldLayout);
  }

  /**
   * @notice Set category.
   */
  function _setCategory(uint32 buildingId, uint32 category) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((category)), _fieldLayout);
  }

  /**
   * @notice Get tribe.
   */
  function getTribe(uint32 buildingId) internal view returns (uint32 tribe) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get tribe.
   */
  function _getTribe(uint32 buildingId) internal view returns (uint32 tribe) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set tribe.
   */
  function setTribe(uint32 buildingId, uint32 tribe) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((tribe)), _fieldLayout);
  }

  /**
   * @notice Set tribe.
   */
  function _setTribe(uint32 buildingId, uint32 tribe) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((tribe)), _fieldLayout);
  }

  /**
   * @notice Get inputItem1.
   */
  function getInputItem1(uint32 buildingId) internal view returns (uint32 inputItem1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get inputItem1.
   */
  function _getInputItem1(uint32 buildingId) internal view returns (uint32 inputItem1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set inputItem1.
   */
  function setInputItem1(uint32 buildingId, uint32 inputItem1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((inputItem1)), _fieldLayout);
  }

  /**
   * @notice Set inputItem1.
   */
  function _setInputItem1(uint32 buildingId, uint32 inputItem1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((inputItem1)), _fieldLayout);
  }

  /**
   * @notice Get inputQty1.
   */
  function getInputQty1(uint32 buildingId) internal view returns (uint64 inputQty1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get inputQty1.
   */
  function _getInputQty1(uint32 buildingId) internal view returns (uint64 inputQty1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set inputQty1.
   */
  function setInputQty1(uint32 buildingId, uint64 inputQty1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((inputQty1)), _fieldLayout);
  }

  /**
   * @notice Set inputQty1.
   */
  function _setInputQty1(uint32 buildingId, uint64 inputQty1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((inputQty1)), _fieldLayout);
  }

  /**
   * @notice Get inputItem2.
   */
  function getInputItem2(uint32 buildingId) internal view returns (uint32 inputItem2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get inputItem2.
   */
  function _getInputItem2(uint32 buildingId) internal view returns (uint32 inputItem2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set inputItem2.
   */
  function setInputItem2(uint32 buildingId, uint32 inputItem2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((inputItem2)), _fieldLayout);
  }

  /**
   * @notice Set inputItem2.
   */
  function _setInputItem2(uint32 buildingId, uint32 inputItem2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((inputItem2)), _fieldLayout);
  }

  /**
   * @notice Get inputQty2.
   */
  function getInputQty2(uint32 buildingId) internal view returns (uint64 inputQty2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get inputQty2.
   */
  function _getInputQty2(uint32 buildingId) internal view returns (uint64 inputQty2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set inputQty2.
   */
  function setInputQty2(uint32 buildingId, uint64 inputQty2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((inputQty2)), _fieldLayout);
  }

  /**
   * @notice Set inputQty2.
   */
  function _setInputQty2(uint32 buildingId, uint64 inputQty2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((inputQty2)), _fieldLayout);
  }

  /**
   * @notice Get outputItem1.
   */
  function getOutputItem1(uint32 buildingId) internal view returns (uint32 outputItem1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get outputItem1.
   */
  function _getOutputItem1(uint32 buildingId) internal view returns (uint32 outputItem1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set outputItem1.
   */
  function setOutputItem1(uint32 buildingId, uint32 outputItem1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((outputItem1)), _fieldLayout);
  }

  /**
   * @notice Set outputItem1.
   */
  function _setOutputItem1(uint32 buildingId, uint32 outputItem1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((outputItem1)), _fieldLayout);
  }

  /**
   * @notice Get outputQty1.
   */
  function getOutputQty1(uint32 buildingId) internal view returns (uint64 outputQty1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get outputQty1.
   */
  function _getOutputQty1(uint32 buildingId) internal view returns (uint64 outputQty1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set outputQty1.
   */
  function setOutputQty1(uint32 buildingId, uint64 outputQty1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((outputQty1)), _fieldLayout);
  }

  /**
   * @notice Set outputQty1.
   */
  function _setOutputQty1(uint32 buildingId, uint64 outputQty1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((outputQty1)), _fieldLayout);
  }

  /**
   * @notice Get outputItem2.
   */
  function getOutputItem2(uint32 buildingId) internal view returns (uint32 outputItem2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get outputItem2.
   */
  function _getOutputItem2(uint32 buildingId) internal view returns (uint32 outputItem2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set outputItem2.
   */
  function setOutputItem2(uint32 buildingId, uint32 outputItem2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((outputItem2)), _fieldLayout);
  }

  /**
   * @notice Set outputItem2.
   */
  function _setOutputItem2(uint32 buildingId, uint32 outputItem2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((outputItem2)), _fieldLayout);
  }

  /**
   * @notice Get outputQty2.
   */
  function getOutputQty2(uint32 buildingId) internal view returns (uint64 outputQty2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get outputQty2.
   */
  function _getOutputQty2(uint32 buildingId) internal view returns (uint64 outputQty2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set outputQty2.
   */
  function setOutputQty2(uint32 buildingId, uint64 outputQty2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((outputQty2)), _fieldLayout);
  }

  /**
   * @notice Set outputQty2.
   */
  function _setOutputQty2(uint32 buildingId, uint64 outputQty2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((outputQty2)), _fieldLayout);
  }

  /**
   * @notice Get name.
   */
  function getName(uint32 buildingId) internal view returns (string memory name) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get name.
   */
  function _getName(uint32 buildingId) internal view returns (string memory name) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set name.
   */
  function setName(uint32 buildingId, string memory name) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((name)));
  }

  /**
   * @notice Set name.
   */
  function _setName(uint32 buildingId, string memory name) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((name)));
  }

  /**
   * @notice Get the length of name.
   */
  function lengthName(uint32 buildingId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of name.
   */
  function _lengthName(uint32 buildingId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of name.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemName(uint32 buildingId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of name.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemName(uint32 buildingId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to name.
   */
  function pushName(uint32 buildingId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to name.
   */
  function _pushName(uint32 buildingId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from name.
   */
  function popName(uint32 buildingId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from name.
   */
  function _popName(uint32 buildingId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of name at `_index`.
   */
  function updateName(uint32 buildingId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of name at `_index`.
   */
  function _updateName(uint32 buildingId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(uint32 buildingId) internal view returns (BuildingTypeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint32 buildingId) internal view returns (BuildingTypeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint32 buildingId,
    uint32 category,
    uint32 tribe,
    uint32 inputItem1,
    uint64 inputQty1,
    uint32 inputItem2,
    uint64 inputQty2,
    uint32 outputItem1,
    uint64 outputQty1,
    uint32 outputItem2,
    uint64 outputQty2,
    string memory name
  ) internal {
    bytes memory _staticData = encodeStatic(
      category,
      tribe,
      inputItem1,
      inputQty1,
      inputItem2,
      inputQty2,
      outputItem1,
      outputQty1,
      outputItem2,
      outputQty2
    );

    EncodedLengths _encodedLengths = encodeLengths(name);
    bytes memory _dynamicData = encodeDynamic(name);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint32 buildingId,
    uint32 category,
    uint32 tribe,
    uint32 inputItem1,
    uint64 inputQty1,
    uint32 inputItem2,
    uint64 inputQty2,
    uint32 outputItem1,
    uint64 outputQty1,
    uint32 outputItem2,
    uint64 outputQty2,
    string memory name
  ) internal {
    bytes memory _staticData = encodeStatic(
      category,
      tribe,
      inputItem1,
      inputQty1,
      inputItem2,
      inputQty2,
      outputItem1,
      outputQty1,
      outputItem2,
      outputQty2
    );

    EncodedLengths _encodedLengths = encodeLengths(name);
    bytes memory _dynamicData = encodeDynamic(name);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint32 buildingId, BuildingTypeData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.category,
      _table.tribe,
      _table.inputItem1,
      _table.inputQty1,
      _table.inputItem2,
      _table.inputQty2,
      _table.outputItem1,
      _table.outputQty1,
      _table.outputItem2,
      _table.outputQty2
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.name);
    bytes memory _dynamicData = encodeDynamic(_table.name);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint32 buildingId, BuildingTypeData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.category,
      _table.tribe,
      _table.inputItem1,
      _table.inputQty1,
      _table.inputItem2,
      _table.inputQty2,
      _table.outputItem1,
      _table.outputQty1,
      _table.outputItem2,
      _table.outputQty2
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.name);
    bytes memory _dynamicData = encodeDynamic(_table.name);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint32 category,
      uint32 tribe,
      uint32 inputItem1,
      uint64 inputQty1,
      uint32 inputItem2,
      uint64 inputQty2,
      uint32 outputItem1,
      uint64 outputQty1,
      uint32 outputItem2,
      uint64 outputQty2
    )
  {
    category = (uint32(Bytes.getBytes4(_blob, 0)));

    tribe = (uint32(Bytes.getBytes4(_blob, 4)));

    inputItem1 = (uint32(Bytes.getBytes4(_blob, 8)));

    inputQty1 = (uint64(Bytes.getBytes8(_blob, 12)));

    inputItem2 = (uint32(Bytes.getBytes4(_blob, 20)));

    inputQty2 = (uint64(Bytes.getBytes8(_blob, 24)));

    outputItem1 = (uint32(Bytes.getBytes4(_blob, 32)));

    outputQty1 = (uint64(Bytes.getBytes8(_blob, 36)));

    outputItem2 = (uint32(Bytes.getBytes4(_blob, 44)));

    outputQty2 = (uint64(Bytes.getBytes8(_blob, 48)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory name) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    name = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (BuildingTypeData memory _table) {
    (
      _table.category,
      _table.tribe,
      _table.inputItem1,
      _table.inputQty1,
      _table.inputItem2,
      _table.inputQty2,
      _table.outputItem1,
      _table.outputQty1,
      _table.outputItem2,
      _table.outputQty2
    ) = decodeStatic(_staticData);

    (_table.name) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint32 buildingId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint32 buildingId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint32 category,
    uint32 tribe,
    uint32 inputItem1,
    uint64 inputQty1,
    uint32 inputItem2,
    uint64 inputQty2,
    uint32 outputItem1,
    uint64 outputQty1,
    uint32 outputItem2,
    uint64 outputQty2
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        category,
        tribe,
        inputItem1,
        inputQty1,
        inputItem2,
        inputQty2,
        outputItem1,
        outputQty1,
        outputItem2,
        outputQty2
      );
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory name) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(name).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory name) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((name)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 category,
    uint32 tribe,
    uint32 inputItem1,
    uint64 inputQty1,
    uint32 inputItem2,
    uint64 inputQty2,
    uint32 outputItem1,
    uint64 outputQty1,
    uint32 outputItem2,
    uint64 outputQty2,
    string memory name
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      category,
      tribe,
      inputItem1,
      inputQty1,
      inputItem2,
      inputQty2,
      outputItem1,
      outputQty1,
      outputItem2,
      outputQty2
    );

    EncodedLengths _encodedLengths = encodeLengths(name);
    bytes memory _dynamicData = encodeDynamic(name);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint32 buildingId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingId));

    return _keyTuple;
  }
}
