// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct BuildingData {
  uint32 buildingTypeId;
  uint32 ownerCharacterId;
  int32 x;
  int32 y;
  uint32 level;
  uint256 lastUsedBlock;
}

library Building {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "aldea", name: "Building", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462616c6465610000000000000000004275696c64696e670000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0034060004040404042000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint32)
  Schema constant _keySchema = Schema.wrap(0x0004010003000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint32, uint32, int32, int32, uint32, uint256)
  Schema constant _valueSchema = Schema.wrap(0x0034060003032323031f00000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "buildingInstanceId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](6);
    fieldNames[0] = "buildingTypeId";
    fieldNames[1] = "ownerCharacterId";
    fieldNames[2] = "x";
    fieldNames[3] = "y";
    fieldNames[4] = "level";
    fieldNames[5] = "lastUsedBlock";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get buildingTypeId.
   */
  function getBuildingTypeId(uint32 buildingInstanceId) internal view returns (uint32 buildingTypeId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get buildingTypeId.
   */
  function _getBuildingTypeId(uint32 buildingInstanceId) internal view returns (uint32 buildingTypeId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set buildingTypeId.
   */
  function setBuildingTypeId(uint32 buildingInstanceId, uint32 buildingTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((buildingTypeId)), _fieldLayout);
  }

  /**
   * @notice Set buildingTypeId.
   */
  function _setBuildingTypeId(uint32 buildingInstanceId, uint32 buildingTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((buildingTypeId)), _fieldLayout);
  }

  /**
   * @notice Get ownerCharacterId.
   */
  function getOwnerCharacterId(uint32 buildingInstanceId) internal view returns (uint32 ownerCharacterId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get ownerCharacterId.
   */
  function _getOwnerCharacterId(uint32 buildingInstanceId) internal view returns (uint32 ownerCharacterId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set ownerCharacterId.
   */
  function setOwnerCharacterId(uint32 buildingInstanceId, uint32 ownerCharacterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((ownerCharacterId)), _fieldLayout);
  }

  /**
   * @notice Set ownerCharacterId.
   */
  function _setOwnerCharacterId(uint32 buildingInstanceId, uint32 ownerCharacterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((ownerCharacterId)), _fieldLayout);
  }

  /**
   * @notice Get x.
   */
  function getX(uint32 buildingInstanceId) internal view returns (int32 x) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get x.
   */
  function _getX(uint32 buildingInstanceId) internal view returns (int32 x) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set x.
   */
  function setX(uint32 buildingInstanceId, int32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Set x.
   */
  function _setX(uint32 buildingInstanceId, int32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Get y.
   */
  function getY(uint32 buildingInstanceId) internal view returns (int32 y) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get y.
   */
  function _getY(uint32 buildingInstanceId) internal view returns (int32 y) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set y.
   */
  function setY(uint32 buildingInstanceId, int32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((y)), _fieldLayout);
  }

  /**
   * @notice Set y.
   */
  function _setY(uint32 buildingInstanceId, int32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((y)), _fieldLayout);
  }

  /**
   * @notice Get level.
   */
  function getLevel(uint32 buildingInstanceId) internal view returns (uint32 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get level.
   */
  function _getLevel(uint32 buildingInstanceId) internal view returns (uint32 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set level.
   */
  function setLevel(uint32 buildingInstanceId, uint32 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((level)), _fieldLayout);
  }

  /**
   * @notice Set level.
   */
  function _setLevel(uint32 buildingInstanceId, uint32 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((level)), _fieldLayout);
  }

  /**
   * @notice Get lastUsedBlock.
   */
  function getLastUsedBlock(uint32 buildingInstanceId) internal view returns (uint256 lastUsedBlock) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get lastUsedBlock.
   */
  function _getLastUsedBlock(uint32 buildingInstanceId) internal view returns (uint256 lastUsedBlock) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set lastUsedBlock.
   */
  function setLastUsedBlock(uint32 buildingInstanceId, uint256 lastUsedBlock) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((lastUsedBlock)), _fieldLayout);
  }

  /**
   * @notice Set lastUsedBlock.
   */
  function _setLastUsedBlock(uint32 buildingInstanceId, uint256 lastUsedBlock) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((lastUsedBlock)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint32 buildingInstanceId) internal view returns (BuildingData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint32 buildingInstanceId) internal view returns (BuildingData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint32 buildingInstanceId,
    uint32 buildingTypeId,
    uint32 ownerCharacterId,
    int32 x,
    int32 y,
    uint32 level,
    uint256 lastUsedBlock
  ) internal {
    bytes memory _staticData = encodeStatic(buildingTypeId, ownerCharacterId, x, y, level, lastUsedBlock);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint32 buildingInstanceId,
    uint32 buildingTypeId,
    uint32 ownerCharacterId,
    int32 x,
    int32 y,
    uint32 level,
    uint256 lastUsedBlock
  ) internal {
    bytes memory _staticData = encodeStatic(buildingTypeId, ownerCharacterId, x, y, level, lastUsedBlock);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint32 buildingInstanceId, BuildingData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.buildingTypeId,
      _table.ownerCharacterId,
      _table.x,
      _table.y,
      _table.level,
      _table.lastUsedBlock
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint32 buildingInstanceId, BuildingData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.buildingTypeId,
      _table.ownerCharacterId,
      _table.x,
      _table.y,
      _table.level,
      _table.lastUsedBlock
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (uint32 buildingTypeId, uint32 ownerCharacterId, int32 x, int32 y, uint32 level, uint256 lastUsedBlock)
  {
    buildingTypeId = (uint32(Bytes.getBytes4(_blob, 0)));

    ownerCharacterId = (uint32(Bytes.getBytes4(_blob, 4)));

    x = (int32(uint32(Bytes.getBytes4(_blob, 8))));

    y = (int32(uint32(Bytes.getBytes4(_blob, 12))));

    level = (uint32(Bytes.getBytes4(_blob, 16)));

    lastUsedBlock = (uint256(Bytes.getBytes32(_blob, 20)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (BuildingData memory _table) {
    (
      _table.buildingTypeId,
      _table.ownerCharacterId,
      _table.x,
      _table.y,
      _table.level,
      _table.lastUsedBlock
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint32 buildingInstanceId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint32 buildingInstanceId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint32 buildingTypeId,
    uint32 ownerCharacterId,
    int32 x,
    int32 y,
    uint32 level,
    uint256 lastUsedBlock
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(buildingTypeId, ownerCharacterId, x, y, level, lastUsedBlock);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 buildingTypeId,
    uint32 ownerCharacterId,
    int32 x,
    int32 y,
    uint32 level,
    uint256 lastUsedBlock
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(buildingTypeId, ownerCharacterId, x, y, level, lastUsedBlock);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint32 buildingInstanceId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(buildingInstanceId));

    return _keyTuple;
  }
}
