// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct RecipeData {
  uint32 input1;
  uint64 inputQty1;
  uint32 input2;
  uint64 inputQty2;
  uint32 input3;
  uint64 inputQty3;
  uint32 output;
  uint64 outputQty;
  uint32 requiredBuildingType;
  bytes32 name;
}

library Recipe {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "aldea", name: "Recipe", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462616c64656100000000000000000052656369706500000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00540a0004080408040804080420000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint32)
  Schema constant _keySchema = Schema.wrap(0x0004010003000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint32, uint64, uint32, uint64, uint32, uint64, uint32, uint64, uint32, bytes32)
  Schema constant _valueSchema = Schema.wrap(0x00540a000307030703070307035f000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "recipeId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](10);
    fieldNames[0] = "input1";
    fieldNames[1] = "inputQty1";
    fieldNames[2] = "input2";
    fieldNames[3] = "inputQty2";
    fieldNames[4] = "input3";
    fieldNames[5] = "inputQty3";
    fieldNames[6] = "output";
    fieldNames[7] = "outputQty";
    fieldNames[8] = "requiredBuildingType";
    fieldNames[9] = "name";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get input1.
   */
  function getInput1(uint32 recipeId) internal view returns (uint32 input1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get input1.
   */
  function _getInput1(uint32 recipeId) internal view returns (uint32 input1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set input1.
   */
  function setInput1(uint32 recipeId, uint32 input1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((input1)), _fieldLayout);
  }

  /**
   * @notice Set input1.
   */
  function _setInput1(uint32 recipeId, uint32 input1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((input1)), _fieldLayout);
  }

  /**
   * @notice Get inputQty1.
   */
  function getInputQty1(uint32 recipeId) internal view returns (uint64 inputQty1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get inputQty1.
   */
  function _getInputQty1(uint32 recipeId) internal view returns (uint64 inputQty1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set inputQty1.
   */
  function setInputQty1(uint32 recipeId, uint64 inputQty1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((inputQty1)), _fieldLayout);
  }

  /**
   * @notice Set inputQty1.
   */
  function _setInputQty1(uint32 recipeId, uint64 inputQty1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((inputQty1)), _fieldLayout);
  }

  /**
   * @notice Get input2.
   */
  function getInput2(uint32 recipeId) internal view returns (uint32 input2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get input2.
   */
  function _getInput2(uint32 recipeId) internal view returns (uint32 input2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set input2.
   */
  function setInput2(uint32 recipeId, uint32 input2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((input2)), _fieldLayout);
  }

  /**
   * @notice Set input2.
   */
  function _setInput2(uint32 recipeId, uint32 input2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((input2)), _fieldLayout);
  }

  /**
   * @notice Get inputQty2.
   */
  function getInputQty2(uint32 recipeId) internal view returns (uint64 inputQty2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get inputQty2.
   */
  function _getInputQty2(uint32 recipeId) internal view returns (uint64 inputQty2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set inputQty2.
   */
  function setInputQty2(uint32 recipeId, uint64 inputQty2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((inputQty2)), _fieldLayout);
  }

  /**
   * @notice Set inputQty2.
   */
  function _setInputQty2(uint32 recipeId, uint64 inputQty2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((inputQty2)), _fieldLayout);
  }

  /**
   * @notice Get input3.
   */
  function getInput3(uint32 recipeId) internal view returns (uint32 input3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get input3.
   */
  function _getInput3(uint32 recipeId) internal view returns (uint32 input3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set input3.
   */
  function setInput3(uint32 recipeId, uint32 input3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((input3)), _fieldLayout);
  }

  /**
   * @notice Set input3.
   */
  function _setInput3(uint32 recipeId, uint32 input3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((input3)), _fieldLayout);
  }

  /**
   * @notice Get inputQty3.
   */
  function getInputQty3(uint32 recipeId) internal view returns (uint64 inputQty3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get inputQty3.
   */
  function _getInputQty3(uint32 recipeId) internal view returns (uint64 inputQty3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set inputQty3.
   */
  function setInputQty3(uint32 recipeId, uint64 inputQty3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((inputQty3)), _fieldLayout);
  }

  /**
   * @notice Set inputQty3.
   */
  function _setInputQty3(uint32 recipeId, uint64 inputQty3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((inputQty3)), _fieldLayout);
  }

  /**
   * @notice Get output.
   */
  function getOutput(uint32 recipeId) internal view returns (uint32 output) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get output.
   */
  function _getOutput(uint32 recipeId) internal view returns (uint32 output) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set output.
   */
  function setOutput(uint32 recipeId, uint32 output) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((output)), _fieldLayout);
  }

  /**
   * @notice Set output.
   */
  function _setOutput(uint32 recipeId, uint32 output) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((output)), _fieldLayout);
  }

  /**
   * @notice Get outputQty.
   */
  function getOutputQty(uint32 recipeId) internal view returns (uint64 outputQty) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get outputQty.
   */
  function _getOutputQty(uint32 recipeId) internal view returns (uint64 outputQty) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set outputQty.
   */
  function setOutputQty(uint32 recipeId, uint64 outputQty) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((outputQty)), _fieldLayout);
  }

  /**
   * @notice Set outputQty.
   */
  function _setOutputQty(uint32 recipeId, uint64 outputQty) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((outputQty)), _fieldLayout);
  }

  /**
   * @notice Get requiredBuildingType.
   */
  function getRequiredBuildingType(uint32 recipeId) internal view returns (uint32 requiredBuildingType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get requiredBuildingType.
   */
  function _getRequiredBuildingType(uint32 recipeId) internal view returns (uint32 requiredBuildingType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set requiredBuildingType.
   */
  function setRequiredBuildingType(uint32 recipeId, uint32 requiredBuildingType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((requiredBuildingType)), _fieldLayout);
  }

  /**
   * @notice Set requiredBuildingType.
   */
  function _setRequiredBuildingType(uint32 recipeId, uint32 requiredBuildingType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((requiredBuildingType)), _fieldLayout);
  }

  /**
   * @notice Get name.
   */
  function getName(uint32 recipeId) internal view returns (bytes32 name) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get name.
   */
  function _getName(uint32 recipeId) internal view returns (bytes32 name) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set name.
   */
  function setName(uint32 recipeId, bytes32 name) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((name)), _fieldLayout);
  }

  /**
   * @notice Set name.
   */
  function _setName(uint32 recipeId, bytes32 name) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((name)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint32 recipeId) internal view returns (RecipeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint32 recipeId) internal view returns (RecipeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint32 recipeId,
    uint32 input1,
    uint64 inputQty1,
    uint32 input2,
    uint64 inputQty2,
    uint32 input3,
    uint64 inputQty3,
    uint32 output,
    uint64 outputQty,
    uint32 requiredBuildingType,
    bytes32 name
  ) internal {
    bytes memory _staticData = encodeStatic(
      input1,
      inputQty1,
      input2,
      inputQty2,
      input3,
      inputQty3,
      output,
      outputQty,
      requiredBuildingType,
      name
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint32 recipeId,
    uint32 input1,
    uint64 inputQty1,
    uint32 input2,
    uint64 inputQty2,
    uint32 input3,
    uint64 inputQty3,
    uint32 output,
    uint64 outputQty,
    uint32 requiredBuildingType,
    bytes32 name
  ) internal {
    bytes memory _staticData = encodeStatic(
      input1,
      inputQty1,
      input2,
      inputQty2,
      input3,
      inputQty3,
      output,
      outputQty,
      requiredBuildingType,
      name
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint32 recipeId, RecipeData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.input1,
      _table.inputQty1,
      _table.input2,
      _table.inputQty2,
      _table.input3,
      _table.inputQty3,
      _table.output,
      _table.outputQty,
      _table.requiredBuildingType,
      _table.name
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint32 recipeId, RecipeData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.input1,
      _table.inputQty1,
      _table.input2,
      _table.inputQty2,
      _table.input3,
      _table.inputQty3,
      _table.output,
      _table.outputQty,
      _table.requiredBuildingType,
      _table.name
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint32 input1,
      uint64 inputQty1,
      uint32 input2,
      uint64 inputQty2,
      uint32 input3,
      uint64 inputQty3,
      uint32 output,
      uint64 outputQty,
      uint32 requiredBuildingType,
      bytes32 name
    )
  {
    input1 = (uint32(Bytes.getBytes4(_blob, 0)));

    inputQty1 = (uint64(Bytes.getBytes8(_blob, 4)));

    input2 = (uint32(Bytes.getBytes4(_blob, 12)));

    inputQty2 = (uint64(Bytes.getBytes8(_blob, 16)));

    input3 = (uint32(Bytes.getBytes4(_blob, 24)));

    inputQty3 = (uint64(Bytes.getBytes8(_blob, 28)));

    output = (uint32(Bytes.getBytes4(_blob, 36)));

    outputQty = (uint64(Bytes.getBytes8(_blob, 40)));

    requiredBuildingType = (uint32(Bytes.getBytes4(_blob, 48)));

    name = (Bytes.getBytes32(_blob, 52));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (RecipeData memory _table) {
    (
      _table.input1,
      _table.inputQty1,
      _table.input2,
      _table.inputQty2,
      _table.input3,
      _table.inputQty3,
      _table.output,
      _table.outputQty,
      _table.requiredBuildingType,
      _table.name
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint32 recipeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint32 recipeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint32 input1,
    uint64 inputQty1,
    uint32 input2,
    uint64 inputQty2,
    uint32 input3,
    uint64 inputQty3,
    uint32 output,
    uint64 outputQty,
    uint32 requiredBuildingType,
    bytes32 name
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        input1,
        inputQty1,
        input2,
        inputQty2,
        input3,
        inputQty3,
        output,
        outputQty,
        requiredBuildingType,
        name
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 input1,
    uint64 inputQty1,
    uint32 input2,
    uint64 inputQty2,
    uint32 input3,
    uint64 inputQty3,
    uint32 output,
    uint64 outputQty,
    uint32 requiredBuildingType,
    bytes32 name
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      input1,
      inputQty1,
      input2,
      inputQty2,
      input3,
      inputQty3,
      output,
      outputQty,
      requiredBuildingType,
      name
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint32 recipeId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(recipeId));

    return _keyTuple;
  }
}
