// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerData } from "./tables/Player.sol";
import { Character, CharacterData } from "./tables/Character.sol";
import { World, WorldData } from "./tables/World.sol";
import { ItemType, ItemTypeData } from "./tables/ItemType.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
import { BuildingType, BuildingTypeData } from "./tables/BuildingType.sol";
import { Building, BuildingData } from "./tables/Building.sol";
import { TribeBonus } from "./tables/TribeBonus.sol";
import { Recipe, RecipeData } from "./tables/Recipe.sol";
import { UserNonce } from "./tables/UserNonce.sol";
import { GameConfig } from "./tables/GameConfig.sol";
