// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBuildingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBuildingSystem {
  function aldea__constructBuilding(
    uint32 characterId,
    uint32 buildingTypeId,
    int32 x,
    int32 y
  ) external returns (uint32);

  function aldea__upgradeBuilding(uint32 buildingInstanceId) external;

  function aldea__destroyBuilding(uint32 buildingInstanceId) external;

  function aldea__isLocationOccupied(int32 x, int32 y) external view returns (bool);

  function aldea__getBuildingAtLocation(int32 x, int32 y) external view returns (uint32);
}
