// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICraftingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICraftingSystem {
  function aldea__craft(uint32 characterId, uint32 buildingInstanceId, uint32 recipeId) external;

  function aldea__extract(uint32 characterId, uint32 buildingInstanceId) external;
}
