// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IInventorySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInventorySystem {
  function aldea__addItem(uint32 characterId, uint32 itemId, uint64 quantity) external;

  function aldea__removeItem(uint32 characterId, uint32 slotIndex, uint64 quantity) external;

  function aldea__transferItem(uint32 fromCharacterId, uint32 fromSlot, uint32 toCharacterId, uint64 quantity) external;

  function aldea__getItemCount(uint32 characterId, uint32 itemId) external view returns (uint64);
}
