// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMovementSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMovementSystem {
  function aldea__moveCharacter(uint32 characterId, int32 newX, int32 newY) external;

  function aldea__teleportCharacter(uint32 characterId, int32 newX, int32 newY) external;

  function aldea__getPosition(uint32 characterId) external view returns (int32 x, int32 y);

  function aldea__isAtLocation(uint32 characterId, int32 x, int32 y) external view returns (bool);
}
