// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IBuildingSystem } from "./IBuildingSystem.sol";
import { ICharacterSystem } from "./ICharacterSystem.sol";
import { ICraftingSystem } from "./ICraftingSystem.sol";
import { IGameInitSystem } from "./IGameInitSystem.sol";
import { IInventorySystem } from "./IInventorySystem.sol";
import { IMovementSystem } from "./IMovementSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IBuildingSystem,
  ICharacterSystem,
  ICraftingSystem,
  IGameInitSystem,
  IInventorySystem,
  IMovementSystem
{}
