[profile.default]
solc = "0.8.24"
via_ir = true
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read", path = "./" }]

[profile.garnet]
eth_rpc_url = "https://rpc.garnetchain.com"

[profile.redstone]
eth_rpc_url = "https://rpc.redstonechain.com"

[etherscan]
17069 = { key = "847e1c16-69be-4776-a0e0-18666a2037b5", chain = 17069, url = "https://explorer.garnetchain.com/api" }
